#!/usr/bin/env bash
set_bspwm_config() {
  bspc config border_width 2
  #  bspc config top_padding 2
  bspc config bottom_padding -1 #2
  bspc config split_ratio 0.5
  bspc config borderless_monocle true
  bspc config window_gap 8
  bspc config gapless_monocle false
  bspc config focus_follows_pointer false
  bspc config left_padding 1                #2
  bspc config right_padding 1               #2
  bspc config normal_border_color "#141b1e" #"#414868"
  bspc config active_border_color "#c0caf5"
  bspc config focused_border_color "#1F2430"
  bspc config presel_feedback_color "#7aa2f7"
}

# Reload terminal colors
set_term_config() {
  cat >"$HOME"/.config/alacritty/rice-colors.toml <<EOF
# (OxoCarbon) color scheme for Yael Rice

# Default colors
[colors.primary]
background = "#141b1e"
foreground = "#cbced3"

# Cursor colors
[colors.cursor]
cursor = "#cbced3"
text = "#1a1b26"

# Normal colors
[colors.normal]
black = "#101419"
red = "#e57474"
green = "#8ccf7e"
yellow = "#e5c76b"
blue =  "#67b0e8"
magenta = "#c47fd5"
cyan = "#6cbfbf"
white = "#b3b9b8"
coklat = "#B6630C"

# Bright colors
[colors.bright]
black = "#1f2328"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#dadada"
EOF
}

# Set kitty colorscheme
set_kitty_config() {
  cat >"$HOME"/.config/kitty/current-theme.conf <<EOF
## This file is autogenerated, do not edit it, instead edit the Theme.sh file inside the rice directory.
## (OxoCarbon) color scheme for Yael Rice


# The basic colors
foreground              #dadada
background              #141b1e
selection_foreground    #141b1e
selection_background    #b3b9b8

# Cursor colors
cursor                  #c47fd5
cursor_text_color       #161616

# URL underline color when hovering with mouse
url_color               #42be65

# Kitty window border colors
active_border_color     #33b1ff
inactive_border_color   #262626
bell_border_color       #ffe97b

# Tab bar colors
active_tab_foreground   #161616
active_tab_background   #33b1ff
inactive_tab_foreground #161616
inactive_tab_background #3ddbd9
tab_bar_background      #161616

# The 16 terminal colors

# black
color0 #141b1e
color8 #232a2d

# red
color1 #e57474
color9 #ee5396

# green
color2  #8ccf7e
color10 #42be65

# yellow
color3  #e5c76b
color11 #ffe97b

# blue
color4  #67b0e8
color12 #33b1ff

# magenta
color5  #c47fd5
color13 #ff7eb6

# cyan
color6  #6cbfbf
color14 #3ddbd9

# white
color7  #dadada
color15 #ffffff
EOF

  killall -USR1 kitty
}

# Set compositor configuration
set_picom_config() {
  sed -i "$HOME"/.config/bspwm/picom.conf \
    -e "s/normal = .*/normal =  { fade = true; shadow = true; }/g" \
    -e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
    -e "s/corner-radius = .*/corner-radius = 6/g" \
    -e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
    -e "s/\".*:class_g = 'kitty'\"/\"100:class_g = 'kitty'\"/g" \
    -e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"
}

# Set dunst notification daemon config
set_dunst_config() {
  sed -i "$HOME"/.config/bspwm/dunstrc \
    -e "s/transparency = .*/transparency = 0/g" \
    -e "s/frame_color = .*/frame_color = \"#1a1b26\"/g" \
    -e "s/separator_color = .*/separator_color = \"#c0caf5\"/g" \
    -e "s/font = .*/font = JetBrainsMono NF Medium 9/g" \
    -e "s/foreground='.*'/foreground='#f9f9f9'/g"

  sed -i '/urgency_low/Q' "$HOME"/.config/bspwm/dunstrc
  cat >>"$HOME"/.config/bspwm/dunstrc <<-_EOF_
		[urgency_low]
		timeout = 3
		background = "#1a1b26"
		foreground = "#c0caf5"

		[urgency_normal]
		timeout = 6
		background = "#1a1b26"
		foreground = "#c0caf5"

		[urgency_critical]
		timeout = 0
		background = "#1a1b26"
		foreground = "#c0caf5"
	_EOF_
}

# Set eww colors
set_eww_colors() {
  cat >"$HOME"/.config/bspwm/eww/colors.scss <<EOF
// Eww colors for Yael rice
\$bg: #141b1e;
\$bg-alt: #232a2d;
\$fg: #dadada;
\$black: #393939;
\$lightblack: #232a2d;
\$red: #e57474;
\$blue: #33b1ff;
\$cyan: #3ddbd9;
\$magenta: #ff7eb6;
\$green: #42be65;
\$yellow: #e5c76b;
\$archicon: #0f94d2;
EOF
}

# Set jgmenu colors for Yael
set_jgmenu_colors() {
  sed -i "$HOME"/.config/bspwm/jgmenurc \
    -e 's/color_menu_bg = .*/color_menu_bg = #141b1e/' \
    -e 's/color_norm_fg = .*/color_norm_fg = #dadada/' \
    -e 's/color_sel_bg = .*/color_sel_bg = #232a2d/' \
    -e 's/color_sel_fg = .*/color_sel_fg = #dadada/' \
    -e 's/color_sep_fg = .*/color_sep_fg = #e5c76b/'
}

# Set rofi colors
set_launcher_config() {
  cat >"$HOME"/.config/bspwm/src/rofi-themes/shared.rasi <<EOF
// Rofi colors for Yael

* {
    font: "JetBrainsMono NF Bold 9";
    background: #141b1e;
    background-alt: #232a2d;
    foreground: #dadada;
    selected: #8ccf7e;
    active: #42be65;
    urgent: #ee5396;
    
    img-background: url("~/.config/bspwm/rices/fawaid.2/rofi.webp", width);
}
EOF
}
#set gtk thema
# Folder konfigurasi GTK
CONFIG_DIR="$HOME/.config/gtk-3.0"
CONFIG_FILE="$CONFIG_DIR/settings.ini"

# Buat folder jika belum ada
#mkdir -p "$CONFIG_DIR"

# Konfigurasi GTK
cat <<EOL >"$CONFIG_FILE"
[Settings]
gtk-theme-name=Everblush
gtk-icon-theme-name=breeze-dark
gtk-font-name=Maple Mono SC NF Bold 9
gtk-cursor-theme-name=Bibata-Modern-Ice
gtk-cursor-theme-size=24
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=1
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
gtk-application-prefer-dark-theme=1
EOL

# Launch the bar
launch_bars() {

  for mon in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$mon polybar -q main -c "${rice_dir}"/config.ini &
  done

}

### ---------- Apply Configurations ---------- ###

set_bspwm_config
set_term_config
set_kitty_config
set_picom_config
set_eww_colors
set_jgmenu_colors
set_dunst_config
set_launcher_config
launch_bars
